[project]
name = "attic-cache"

[[services]]
name = "attic"
dockerfile = "Dockerfile"
ports = [8080]
resources = { cpu = 0.5, memory = 512 }
env = [
  { name = "ATTIC_SERVER_DATABASE_URL", value = "${{DATABASE_URL}}" },
  { name = "ATTIC_SERVER_TOKEN_HS256_SECRET_BASE64", value = '${{secret(86, "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789+/")}}' },
]

[[databases]]
name = "postgres"
engine = "postgres"
